-- 错误代码
Errcode = {}

Errcode.timeout = 0
Errcode.ok = 1
Errcode.error = -1
Errcode.needregist = 2 -- 未注册
Errcode.uidregisted = 3 -- uid已经被注册
Errcode.psderror = 4 -- 密码错误
Errcode.toomanydevice = 5 -- 设备超限
Errcode.outOfMaxLev = 6 -- 已经是最高等级
Errcode.resNotEnough = 7 -- 资源不足
Errcode.exceedHeadquarters = 8 -- 不能超过主基地等级
Errcode.noIdelQueue = 9 -- 没有空闲队列
Errcode.maxNumber = 10 -- 数量已达上限
Errcode.cannotPlace = 11 -- 不可放下
Errcode.tileIsNil = 12 -- 取得地块为空
Errcode.buildingIsNil = 13 -- 取得建筑为空
Errcode.tileListIsNil = 14 -- 地块信息列表为空
Errcode.cityIsNil = 15 -- 主城为空
Errcode.buildingListIsNil = 16 -- 建筑信息列表为空
Errcode.buildingNotIdel = 17 -- 建筑的状态不是空闲状态
Errcode.playerIsNil = 18 -- 玩家数据取得为空
Errcode.diamNotEnough = 19 -- 钻石不足
Errcode.buildingIsBusy = 20 -- 建筑正忙，不可操作
Errcode.buildingIsNotResFactory = 21 -- 不是资源建筑，不可操作
Errcode.storeNotEnough = 22 -- 仓库空间不足
Errcode.numError = 23 -- 数量错误
Errcode.cfgIsNil = 24 -- 取得配置数据为空
Errcode.shipIsLocked = 25 -- 航船未解锁
Errcode.dockyardSpaceNotEnough = 26 -- 船坞空间不足
Errcode.notInGridBounds = 27 -- 无效的世界坐标
Errcode.worldCellNotIdel = 28 -- 当前坐标不是空闲
Errcode.notFoundInWorld = 29 -- 世界地图中没找到玩家城
Errcode.protectedCannotAttack = 30 -- 玩家处在免战保护中，不可攻击
Errcode.fleetIsNil = 31 -- 舰队不存在
Errcode.fleetsReachedMax = 32 -- 已经超过最大舰队数量
Errcode.toposisCurPos = 33 -- 目标坐标与当前坐标一致
Errcode.foodNotEnough = 34 -- 粮食不足
Errcode.goldNotEnough = 35 -- 金币不足
Errcode.oilNotEnough = 36 -- 油不足
Errcode.diamNotEnough = 37 -- 钻石不足
Errcode.fleetCannotMoveTo = 38 -- 舰队不能到达
Errcode.cannontFoundPlayerInWorld = 39 -- 无法在世界地图上找到玩家
Errcode.toFarCannotAttack = 40 -- 距离太远无法进行攻击
Errcode.fleetIsNotMine = 41 -- 舰队不是自己的，不可操作
Errcode.targetBeingAttackedCannotAttack = 42 -- 玩家正在被其它玩家攻击，暂时不可攻击
Errcode.unitNotEnough = 43 -- 战斗单元数量不足
Errcode.reportIsNil = 44 -- 战报数据为空
Errcode.mailIsNil = 45 -- 邮件为空
Errcode.mailHadReaded = 46 -- 邮件已经读过
Errcode.rewardNot4Player = 47 -- 该奖励包不属于此玩家
Errcode.rewardIsNil = 48 -- 奖励包为空
Errcode.itemNotEnough = 49 -- 道具数量不足
Errcode.itemIsNil = 50 -- 道具为空
Errcode.boxIsNil = 51 -- 宝箱为空
Errcode.levTooLowCannotChatInWorld = 52 -- 玩家等级太低，不能在世界频道发言
Errcode.contentIsNil = 53 -- 内容为空
Errcode.contentOverLen = 54 -- 内容超长
Errcode.fleetIsFighting = 55 -- 舰队正在战斗中，不可操作
Errcode.overofPvPTimes = 56 -- 今日的攻击的次数已经用完
Errcode.techIsNil = 57 -- 科技为空
Errcode.exceedTech = 58 -- 不能超过科技中心等级
Errcode.techIsLocked = 59 -- 科技还未解锁
Errcode.noUpgradingTech = 60 -- 没有正在升级的科技
Errcode.magicIsLocked = 61 -- 魔法未解锁
Errcode.maximumLimitReached = 62 -- 数量达上限
Errcode.nothingTodo = 63 -- 无可操作的对象
return Errcode
