---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenbin.
--- DateTime: 18/12/12 17:18
---
--======================================================
--======================================================
---@class 各种队列处理
timerQueue = {
    build = {}, -- 建筑队列
    ship = {}, -- 兵队列
    tech = {}, -- 科技队列
}

---@public 加入建筑队列
---@param b dbbuilding
timerQueue.addtimerQueue = function(b, callback)
    local endtime = b:get_endtime()
    local diff = endtime - dateEx.nowMS()
    local cor = timerEx.new(diff / 1000, callback, b)
    table.insert(timerQueue.build, cor)
end

---@param b dbbuilding
timerQueue.removetimerQueue = function(b)
    ---@type dbbuilding
    local building
    for i, cor in ipairs(timerQueue.build) do
        building = cor.param
        if building:get_idx() == b:get_idx() then
            timerEx.cancel(cor) --取消timer
            table.remove(timerQueue.build, i)
            break
        end
    end
end

---@public 加入造兵队列
---@param b dbbuilding
timerQueue.addShipQueue = function(b, seconds, callback)
    if b:get_state() ~= IDConstVals.BuildingState.working then
        timerQueue.removeShipQueue(b)
        return
    end
    local roleAttrId = b:get_val()
    local num = b:get_val2()
    if num <= 0 then
        timerQueue.removeShipQueue(b)
        return
    end

    local cor = timerEx.new(seconds, callback, b)
    timerQueue.ship[b:get_idx()] = cor
end

---@param b dbbuilding
timerQueue.removeShipQueue = function(b)
    local cor = timerQueue.ship[b:get_idx()]
    if cor then
        timerEx.cancel(cor) --取消timer
    end
    timerQueue.ship[b:get_idx()] = nil
end

timerQueue.release = function()
    for i, v in ipairs(timerQueue.build) do
        timerEx.cancel(v)
    end
    timerQueue.build = {}

    for i, v in ipairs(timerQueue.ship) do
        timerEx.cancel(v)
    end
    timerQueue.ship = {}
    
    for i, v in ipairs(timerQueue.tech) do
        timerEx.cancel(v)
    end
    timerQueue.tech = {}
end

return timerQueue
